#org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.incremental=true
android.enableJetifier=true
# ?????? ??? ?????? ??? ?????????? ?????????????? ? compileSdk
android.suppressUnsupportedCompileSdk=36

# ????????? ??????????? ????? Room (?????????? AccessDeniedException)
android.experimental.enableArtifacts=true
kapt.use.worker.api=false
kapt.include.compile.classpath=false

# ????????????? ?????? ????????? ?????????? ? ???????? ????????????
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8